import ReactMarkdown from "react-markdown";
import { useFetcher } from "react-router";
import {
    Box,
    Card,
    Title,
    Text,
    Stack,
    Divider,
    Button,
    Center,
    Loader,
} from "@mantine/core";
import { IconArticle, IconSparkles } from "@tabler/icons-react";

/**
 * GameRecapView Component
 * Renders a gorgeous, newspaper-style editorial markdown recap of a softball game.
 * If no recap is present but logs are available, displays a beautiful, premium CTA
 * to explicitly trigger the Gemini AI Recap generator.
 *
 * @param {Object} props - Component properties
 * @param {string} [props.recap] - The raw markdown recap text generated by Gemini
 * @param {Array} [props.logs=[]] - Chronological logs to verify play-by-play presence
 * @param {boolean} [props.isScorekeeper=false] - If true, displays the AI trigger button
 * @returns {JSX.Element|null}
 */
export default function GameRecapView({
    recap,
    logs = [],
    isScorekeeper = false,
}) {
    const fetcher = useFetcher();
    const isGenerating = fetcher.state !== "idle";

    // 1. Render the Generate Recap Call-To-Action if recap is not yet generated
    if (!recap) {
        if (logs.length === 0) return null;

        return (
            <Card
                radius="lg"
                p={{ base: "xl", md: 40 }}
                ta="center"
                style={{
                    border: "1px dashed light-dark(rgba(9, 133, 0, 0.3), rgba(204, 255, 51, 0.3))",
                }}
            >
                <Stack align="center" gap="lg">
                    <Center
                        style={{
                            width: 60,
                            height: 60,
                            borderRadius: "50%",
                            background:
                                "light-dark(rgba(9, 133, 0, 0.1), rgba(204, 255, 51, 0.1))",
                            color: "light-dark(var(--mantine-color-lime-9), #CCFF33)",
                        }}
                    >
                        <IconSparkles size={32} stroke={1.5} />
                    </Center>

                    <Stack gap="xs">
                        <Title
                            order={2}
                            style={{ fontFamily: "Open Sans, sans-serif" }}
                        >
                            No Game Recap Yet
                        </Title>
                        <Text
                            size="sm"
                            c="dimmed"
                            ta="center"
                            style={{ lineHeight: 1.6 }}
                        >
                            This game was finalized without generating a recap.
                            If you are a scorekeeper or manager, you can
                            generate a personalized, premium sports column recap
                            built from the play-by-play logs.
                        </Text>
                    </Stack>

                    {isScorekeeper ? (
                        <fetcher.Form method="post">
                            <input
                                type="hidden"
                                name="_action"
                                value="generate-recap"
                            />
                            <Button
                                type="submit"
                                variant="filled"
                                color="lime"
                                size="md"
                                radius="md"
                                fz="lg"
                                disabled={isGenerating}
                                leftSection={
                                    isGenerating ? (
                                        <Loader
                                            size="xs"
                                            color="light-dark(white, black)"
                                        />
                                    ) : (
                                        <IconSparkles size={18} />
                                    )
                                }
                                style={{
                                    boxShadow:
                                        "0 4px 14px light-dark(rgba(9, 133, 0, 0.25), rgba(204, 255, 51, 0.3))",
                                }}
                            >
                                {isGenerating
                                    ? "Writing Recap Column..."
                                    : "Generate AI Recap"}
                            </Button>
                        </fetcher.Form>
                    ) : (
                        <Text size="xs" c="dimmed" fs="italic">
                            Ask a team manager or scorekeeper to generate the
                            recap column.
                        </Text>
                    )}
                </Stack>
            </Card>
        );
    }

    // 2. Render the generated sports recap column
    return (
        <Card radius="lg" p={{ base: "md", md: "xl" }}>
            <Stack gap="lg">
                {/* Header Icon and Label */}
                <Box
                    style={{
                        display: "flex",
                        alignItems: "center",
                        gap: "10px",
                        color: "light-dark(var(--mantine-color-lime-9), #CCFF33)", // high-visibility accent
                    }}
                >
                    <IconArticle size={26} stroke={1.5} />
                    <Text
                        fw={700}
                        size="sm"
                        style={{
                            letterSpacing: "1px",
                            textTransform: "uppercase",
                        }}
                    >
                        AI Sports Column
                    </Text>
                </Box>

                <Divider />

                {/* Editorial Markdown Body */}
                <Box
                    className="editorial-body"
                    style={{
                        fontFamily: "Georgia, serif", // editorial newspaper style
                        fontSize: "1.1rem",
                        lineHeight: "1.75",
                    }}
                >
                    <ReactMarkdown
                        components={{
                            h1: ({ node, ...props }) => (
                                <Title
                                    order={1}
                                    mt="xs"
                                    mb="lg"
                                    style={{
                                        fontFamily: "Open Sans, sans-serif",
                                        fontSize: "1.6rem",
                                        fontWeight: 800,
                                        lineHeight: "1.3",
                                    }}
                                    {...props}
                                />
                            ),
                            h2: ({ node, ...props }) => (
                                <Title
                                    order={2}
                                    mt="xl"
                                    mb="md"
                                    style={{
                                        fontFamily: "Open Sans, sans-serif",
                                        fontSize: "1.4rem",
                                        fontWeight: 700,
                                        color: "light-dark(var(--mantine-color-lime-9), #CCFF33)", // high contrast lime/neon accent
                                    }}
                                    {...props}
                                />
                            ),
                            p: ({ node, ...props }) => (
                                <p
                                    style={{
                                        marginBottom: "1.2rem",
                                        textAlign: "justify",
                                    }}
                                    {...props}
                                />
                            ),
                            li: ({ node, ...props }) => (
                                <li
                                    style={{
                                        marginBottom: "0.5rem",
                                        listStyleType: "square",
                                    }}
                                    {...props}
                                />
                            ),
                            strong: ({ node, ...props }) => (
                                <strong
                                    style={{
                                        fontWeight: 700,
                                    }}
                                    {...props}
                                />
                            ),
                        }}
                    >
                        {recap}
                    </ReactMarkdown>
                </Box>
            </Stack>
        </Card>
    );
}
