#!/usr/bin/env sh

# Load NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Use .nvmrc or default
if command -v nvm >/dev/null; then
  nvm use --silent 2>/dev/null || nvm use default --silent 2>/dev/null
fi

# Run lint-staged
npx lint-staged
